### ISSUE TITLE
PHP Warning: Non-static method BlockChyp\BlockChypClient::getOfflineRoute() should not be called statically

### ISSUE THREAD

**Issue by blasto333** [blockchyp/blockchyp-php#3]
Calling code below results in php errors below (NOTE: The API call still works just php errors)

     // Populate request values
		$request = [
			'test' => $this->test_mode,
			'terminalName' => $this->emv_terminal_id,
		    'transaction' => [
		        'subtotal' => '60.00',
		        'tax' => '5.00',
		        'total' => '65.00',
		        'items' => [
		            [
		                'description' => 'Leki Trekking Poles',
		                'price' => '35.00',
		                'quantity' => 2,
		                'extended' => '70.00',
		                'discounts' => [
		                    [
		                        'description' => 'memberDiscount',
		                        'amount' => '10.00',
		                    ],
		                ],
		            ],
		        ],
		    ],
		];
		
		BlockChyp::newTransactionDisplay($request);

Severity: 8192

Message: Non-static method BlockChyp\BlockChypClient::getOfflineRoute() should not be called statically

Filename: lib/BlockChypClient.php

Line Number: 205

Here is the error chunk

```
 private static function routeCacheGet($terminalName, $stale = false)
    {
        $cacheKey = self::toRouteKey($terminalName, self::$apiKey);

        if (isset(self::$routeCache[$cacheKey])) {
            $localRoute = self::$routeCache[$cacheKey];

            if (self::validRoute($localRoute, $stale)) {
                return $localRoute;
            }
        }

        if (self::$offlineCacheEnabled) {
            **$offlineRoute = self::getOfflineRoute($cacheKey);**
            if (self::validRoute($offlineRoute, $stale)) {
                self::$routeCache[$cacheKey] = $offlineRoute;
                return $offlineRoute;
            }
        }

        return false;
    }
```

**Comment by jniedrauer** [comment]
Thank you for reporting this. We'll have it fixed shortly.

**Comment by jniedrauer** [comment]
This should be fixed. Please let me know if you're still able to reproduce.

**Comment by blasto333** [comment]
From composer 2.9.3 it is still happeing. Here are all errors when doing a charge

            "name": "blockchyp/blockchyp-php",
            "version": "v2.9.3",
            "source": {
                "type": "git",
                "url": "https://github.com/blockchyp/blockchyp-php.git",
                "reference": "6372fe93422a41caaabef2bfb3f5216305b55adc"
            },


A PHP Error was encountered

Severity: 8192

Message: Non-static method BlockChyp\BlockChypClient::routeTerminalRequest() should not be called statically

Filename: lib/BlockChyp.php

Line Number: 46

Backtrace:

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChyp.php
Line: 46
Function: _error_handler

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/Coreclearblockchypprocessor.php
Line: 98
Function: charge

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/controllers/Sales.php
Line: 1695
Function: do_start_cc_processing

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/index.php
Line: 467
Function: require_once

A PHP Error was encountered

Severity: 8192

Message: Non-static method BlockChyp\BlockChypClient::resolveTerminalRoute() should not be called statically

Filename: lib/BlockChypClient.php

Line Number: 135

Backtrace:

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 135
Function: _error_handler

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChyp.php
Line: 46
Function: routeTerminalRequest

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/Coreclearblockchypprocessor.php
Line: 98
Function: charge

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/controllers/Sales.php
Line: 1695
Function: do_start_cc_processing

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/index.php
Line: 467
Function: require_once

A PHP Error was encountered

Severity: 8192

Message: Non-static method BlockChyp\BlockChypClient::routeCacheGet() should not be called statically

Filename: lib/BlockChypClient.php

Line Number: 291

Backtrace:

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 291
Function: _error_handler

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 135
Function: resolveTerminalRoute

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChyp.php
Line: 46
Function: routeTerminalRequest

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/Coreclearblockchypprocessor.php
Line: 98
Function: charge

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/controllers/Sales.php
Line: 1695
Function: do_start_cc_processing

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/index.php
Line: 467
Function: require_once

A PHP Error was encountered

Severity: 8192

Message: Non-static method BlockChyp\BlockChypClient::getOfflineRoute() should not be called statically

Filename: lib/BlockChypClient.php

Line Number: 205

Backtrace:

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 205
Function: _error_handler

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 291
Function: routeCacheGet

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 135
Function: resolveTerminalRoute

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChyp.php
Line: 46
Function: routeTerminalRequest

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/Coreclearblockchypprocessor.php
Line: 98
Function: charge

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/controllers/Sales.php
Line: 1695
Function: do_start_cc_processing

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/index.php
Line: 467
Function: require_once

A PHP Error was encountered

Severity: 8192

Message: Non-static method BlockChyp\BlockChypClient::getCacheLocation() should not be called statically

Filename: lib/BlockChypClient.php

Line Number: 244

Backtrace:

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 244
Function: _error_handler

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 205
Function: getOfflineRoute

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 291
Function: routeCacheGet

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 135
Function: resolveTerminalRoute

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChyp.php
Line: 46
Function: routeTerminalRequest

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/Coreclearblockchypprocessor.php
Line: 98
Function: charge

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/controllers/Sales.php
Line: 1695
Function: do_start_cc_processing

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/index.php
Line: 467
Function: require_once

A PHP Error was encountered

Severity: 8192

Message: Non-static method BlockChyp\BlockChypClient::validRoute() should not be called statically

Filename: lib/BlockChypClient.php

Line Number: 206

Backtrace:

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 206
Function: _error_handler

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 291
Function: routeCacheGet

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 135
Function: resolveTerminalRoute

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChyp.php
Line: 46
Function: routeTerminalRequest

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/Coreclearblockchypprocessor.php
Line: 98
Function: charge

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/controllers/Sales.php
Line: 1695
Function: do_start_cc_processing

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/index.php
Line: 467
Function: require_once

A PHP Error was encountered

Severity: 8192

Message: Non-static method BlockChyp\BlockChypClient::validRouteTime() should not be called statically

Filename: lib/BlockChypClient.php

Line Number: 226

Backtrace:

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 226
Function: _error_handler

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 206
Function: validRoute

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 291
Function: routeCacheGet

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChypClient.php
Line: 135
Function: resolveTerminalRoute

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/blockchyp/vendor/blockchyp/blockchyp-php/lib/BlockChyp.php
Line: 46
Function: routeTerminalRequest

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/libraries/Coreclearblockchypprocessor.php
Line: 98
Function: charge

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/application/controllers/Sales.php
Line: 1695
Function: do_start_cc_processing

File: /Users/cmuench/Sites/localhost/phppos/PHP-Point-Of-Sale/index.php
Line: 467

**Comment by jniedrauer** [comment]
What version of PHP are you using?

**Comment by blasto333** [comment]
7.3.24
--
Chris Muench
Direct +1 585-880-6599

**Comment by jniedrauer** [comment]
I've pushed a new tag (v2.9.4). Let me know if you can still reproduce after updating. Thanks

**Comment by blasto333** [comment]
Works great now with no errors!
--
Chris Muench
Direct +1 585-880-6599
